# Generated by Django 4.2.2 on 2023-06-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
